### PR TITLE
add debian os support, and convert  to 16 bit that my linux could sup…

### PR DESCRIPTION
**Pull request by zjsxwc**
改了下代码能让我在deepin下编译后运行,
以及把`win.wav`音频编码转换成16位音频，貌似我sdl不能支持24位的wav音频

### CODE REVIEW

**Comment by yujqiao** [comment]
I think the failure of compilation is caused by the difference of the default standard used by different `gcc`. I'd like to change `Makefile` rather than hardcode the constants.
Could you please try compile with `-std=c99`? Change the line in your `Makefile` to this:
```
CFLAGS = -g -Wall -std=c99
```

**Comment by zjsxwc** [comment]
> I think the failure of compilation is caused by the difference of the default standard used by different `gcc`. I'd like to change `Makefile` rather than hardcode the constants.
> Could you please try compile with `-std=c99`? Change the line in your `Makefile` to this:
> 
> ```
> CFLAGS = -g -Wall -std=c99
> ```

l get the same error as before, when i compile with `-std=c99` option.

**Comment by yujqiao** [comment]
I can compile it without errors on Arch Linux.
At a later time, I will test it on Ubuntu and consider how we handle the constants.

**Comment by zjsxwc** [comment]
> I can compile it without errors on Arch Linux.
> At a later time, I will test it on Ubuntu and consider how we handle the constants.

I removed the code in my new commit.
It seems that the constants `SCREEN_FPS` and `SCREEN_TICKS_PER_FRAME` are not used in the project.

And maybe your compiler is smart enough to auto remove the unused code, so you could compile it without errors.

**Comment by yujqiao** [comment]
> > I can compile it without errors on Arch Linux.
> > At a later time, I will test it on Ubuntu and consider how we handle the constants.
> 
> I removed the code in my new commit.
> It seems that the constants `SCREEN_FPS` and `SCREEN_TICKS_PER_FRAME` are not used in the project.
> 
> And maybe your compiler is smart enough to auto remove the unused code, so you could compile it without errors.

😲 You're right. In the late stage of the development, I use SDL2 flag `SDL_RENDERER_PRESENTVSYNC` to capture the FPS so they are no longer needed.
Thanks for your contribution.

**Pull request merged**
